# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: root

production:
  <<: *default
  database: pint_production
  pool: 5
  username: xxxxxxxxx
  password: xxxxxxxxx

development:
  <<: *default
  database: pint_development

test:
  <<: *default
  database: pint_test